/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package perbankan.ui.nasabah;

import perbankan.application.repositories.auth.AuthRepository;
import perbankan.application.repositories.nasabah.NasabahRepository;
import perbankan.application.services.DatabaseService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import perbankan.InjectionContainer;
import perbankan.models.Bank;
import perbankan.models.Nasabah;
import perbankan.models.User;
import perbankan.ui.MainFrame;
import perbankan.ui.dashboard.DashboardView;
import perbankan.ui.transaksi.TransaksiView;

/**
 *
 * @author MSI
 */
public class NasabahView extends javax.swing.JPanel {

    private final Bank bank;
    private final MainFrame mainFrame;
    private NasabahListTableModel tableModel;
    private boolean isEdit = false;
    private boolean isSelectionUserEvent = false;
    private final NasabahRepository repository;
    private final AuthRepository authRepository;
    private List<User> cbItemList;

    /**
     * Creates new form NasabahView
     *
     * @param mainFrame
     */
    public NasabahView(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        authRepository = InjectionContainer.authRepository;
        repository = InjectionContainer.nasabahRepository;
        bank = DatabaseService.getBank();
        tableModel = new NasabahListTableModel(bank.getNasabah());
        initComponents();
        fillAccountNumberField();
        initCbItems();
        nasabahListTable.setModel(tableModel);
        ListSelectionModel list = nasabahListTable.getSelectionModel();
        setEditingMode();
        // Listen to row selection
        list.addListSelectionListener((ListSelectionEvent e) -> {
            if (!e.getValueIsAdjusting() && !isSelectionUserEvent) {
                initCbItems();
                isEdit = true;
                int selectedRow = nasabahListTable.getSelectedRow();
                if (selectedRow != -1) {
                    Nasabah data = tableModel.getNasabahAt(selectedRow);
                    tfAccountNumber.setText(data.getNoRekening());
                    tfFirstName.setText(data.getNamaAwal());
                    tfLastName.setText(data.getNamaAkhir());
                    if (data.getUser() != null) {
                        cbItemList.add(data.getUser());
                        cbUser.addItem(data.getUser().getUsername());
                        cbUser.setSelectedIndex(cbItemList.size() - 1);
                    }
                }
                setEditingMode();
            }
        });
    }

    private void fillAccountNumberField() {
        String accountNumber = UniqueAccountNumberGenerator.generateUniqueValue(10);
        tfAccountNumber.setText(accountNumber);
    }

    private void initCbItems() {
        cbItemList = authRepository.getAllUsers();
        cbUser.removeAllItems();
        for (int i = 0; i < cbItemList.size(); i++) {
            cbUser.addItem(cbItemList.get(i).getUsername());
        }
    }

    private void setEditingMode() {
        btnNasabahAction.setText(isEdit ? "Ubah" : "Tambah");
        btnCancelNasabah.setVisible(isEdit);
        btnDeleteNasabah.setVisible(isEdit);
        btnTransaksi.setVisible(isEdit);
        if (!isEdit) {
            clearTextFields();
            isSelectionUserEvent = true;
            nasabahListTable.clearSelection();
            isSelectionUserEvent = false;
            fillAccountNumberField();
        }
    }

    private void clearTextFields() {
        tfFirstName.setText("");
        tfLastName.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfLastName = new javax.swing.JTextField();
        btnNasabahAction = new javax.swing.JButton();
        btnDeleteNasabah = new javax.swing.JButton();
        btnCancelNasabah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nasabahListTable = new javax.swing.JTable();
        btnTransaksi = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbUser = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tfAccountNumber = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Manajemen Nasabah");

        jLabel2.setText("Nama Awal");

        jLabel3.setText("Nama Akhir");

        btnNasabahAction.setText("Tambah");
        btnNasabahAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNasabahActionActionPerformed(evt);
            }
        });

        btnDeleteNasabah.setText("Hapus");
        btnDeleteNasabah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNasabahActionPerformed(evt);
            }
        });

        btnCancelNasabah.setText("Batal");
        btnCancelNasabah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelNasabahActionPerformed(evt);
            }
        });

        nasabahListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(nasabahListTable);

        btnTransaksi.setText("Transaksi");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel4.setText("User");

        cbUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("No Rekening");

        tfAccountNumber.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfAccountNumber.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnBack)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(21, 21, 21)
                                    .addComponent(tfAccountNumber))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addGap(21, 21, 21)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfFirstName)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnNasabahAction, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnDeleteNasabah)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnTransaksi)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnCancelNasabah, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(tfLastName)
                                        .addComponent(cbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNasabahAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteNasabah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTransaksi))
                    .addComponent(btnCancelNasabah))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNasabahActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNasabahActionActionPerformed
        String firstName = tfFirstName.getText();
        String lastName = tfLastName.getText();
        String accountNumber = tfAccountNumber.getText();
        try {
            User user = cbItemList.get(cbUser.getSelectedIndex());
            Nasabah nasabah = new Nasabah(accountNumber, firstName, lastName, user);
            if (firstName.trim().isEmpty() || lastName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Field harus diisi!");
                return;
            }
            if (isEdit) {
                int index = nasabahListTable.getSelectedRow();
                repository.editNasabah(index, firstName, lastName, user);
                tableModel.fireTableDataChanged();
            } else {
                repository.addNasabah(nasabah);
                if (tableModel.getRowCount() == 0) {
                    tableModel.setNasabahList(bank.getNasabah());
                }
                tableModel.fireTableRowsInserted(0, bank.getJumlahNasabah() - 1);
                clearTextFields();
                fillAccountNumberField();
            }
            initCbItems();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tidak ada user yang tersedia!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNasabahActionActionPerformed

    private void btnDeleteNasabahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNasabahActionPerformed
        int index = nasabahListTable.getSelectedRow();
        bank.deleteNasabah(index);
        tableModel.fireTableDataChanged();
        isEdit = false;
        setEditingMode();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteNasabahActionPerformed

    private void btnCancelNasabahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelNasabahActionPerformed
        isEdit = false;
        initCbItems();
        setEditingMode();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelNasabahActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        int selectedRow = nasabahListTable.getSelectedRow();
        if (selectedRow != -1) {
            Nasabah data = tableModel.getNasabahAt(selectedRow);
            mainFrame.showView(new TransaksiView(mainFrame, data));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainFrame.showView(new DashboardView(mainFrame));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancelNasabah;
    private javax.swing.JButton btnDeleteNasabah;
    private javax.swing.JButton btnNasabahAction;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JComboBox<String> cbUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable nasabahListTable;
    private javax.swing.JTextField tfAccountNumber;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfLastName;
    // End of variables declaration//GEN-END:variables
}
